const dashboardData = {
    "last_updated": "2026-06-27 06:51:32",
    "countdown_target": "2026-06-11T19:00:00",
    "news": [
        {
            "title": "WM 2026: Gruppe G - Belgien feiert Gruppensieg – Iran verpasst direktes Weiterkommen",
            "date": "27.06.2026",
            "image": "https://www.srf.ch/static/cms/images/320ws/52d997a.webp"
        },
        {
            "title": "WM 2026: Gruppe H - Uruguay unterliegt Spanien und ist out – Kap Verde in K.o.-Phase",
            "date": "27.06.2026",
            "image": "https://www.srf.ch/static/cms/images/320ws/d4fac90.webp"
        }
    ],
    "schedule": {
        "today_games": [
            {
                "team1": "Uruguay",
                "team1_country": "uy",
                "team2": "Spanien",
                "team2_country": "es",
                "date_str": "Sa, 27. Juni",
                "time": "02:00",
                "venue": "Group H",
                "state": "Finished",
                "score": "0 : 1",
                "full_date": "2026-06-27T02:00:00",
                "group": "GROUP_H",
                "type": "group"
            },
            {
                "team1": "Cape Verde Islands",
                "team1_country": "",
                "team2": "Saudi-Arabien",
                "team2_country": "sa",
                "date_str": "Sa, 27. Juni",
                "time": "02:00",
                "venue": "Group H",
                "state": "Finished",
                "score": "0 : 0",
                "full_date": "2026-06-27T02:00:00",
                "group": "GROUP_H",
                "type": "group"
            },
            {
                "team1": "Neuseeland",
                "team1_country": "nz",
                "team2": "Belgien",
                "team2_country": "be",
                "date_str": "Sa, 27. Juni",
                "time": "05:00",
                "venue": "Group G",
                "state": "Finished",
                "score": "1 : 5",
                "full_date": "2026-06-27T05:00:00",
                "group": "GROUP_G",
                "type": "group"
            },
            {
                "team1": "Ägypten",
                "team1_country": "eg",
                "team2": "Iran",
                "team2_country": "ir",
                "date_str": "Sa, 27. Juni",
                "time": "05:00",
                "venue": "Group G",
                "state": "Finished",
                "score": "1 : 1",
                "full_date": "2026-06-27T05:00:00",
                "group": "GROUP_G",
                "type": "group"
            },
            {
                "team1": "Panama",
                "team1_country": "pa",
                "team2": "England",
                "team2_country": "gb-eng",
                "date_str": "Sa, 27. Juni",
                "time": "23:00",
                "venue": "Group L",
                "state": "Planned",
                "score": null,
                "full_date": "2026-06-27T23:00:00",
                "group": "GROUP_L",
                "type": "group"
            },
            {
                "team1": "Kroatien",
                "team1_country": "hr",
                "team2": "Ghana",
                "team2_country": "gh",
                "date_str": "Sa, 27. Juni",
                "time": "23:00",
                "venue": "Group L",
                "state": "Planned",
                "score": null,
                "full_date": "2026-06-27T23:00:00",
                "group": "GROUP_L",
                "type": "group"
            }
        ],
        "past_results": [
            {
                "team1": "Neuseeland",
                "team1_country": "nz",
                "team2": "Belgien",
                "team2_country": "be",
                "date_str": "Sa, 27. Juni",
                "time": "05:00",
                "venue": "Group G",
                "state": "Finished",
                "score": "1 : 5",
                "full_date": "2026-06-27T05:00:00",
                "group": "GROUP_G",
                "type": "group"
            },
            {
                "team1": "Ägypten",
                "team1_country": "eg",
                "team2": "Iran",
                "team2_country": "ir",
                "date_str": "Sa, 27. Juni",
                "time": "05:00",
                "venue": "Group G",
                "state": "Finished",
                "score": "1 : 1",
                "full_date": "2026-06-27T05:00:00",
                "group": "GROUP_G",
                "type": "group"
            },
            {
                "team1": "Uruguay",
                "team1_country": "uy",
                "team2": "Spanien",
                "team2_country": "es",
                "date_str": "Sa, 27. Juni",
                "time": "02:00",
                "venue": "Group H",
                "state": "Finished",
                "score": "0 : 1",
                "full_date": "2026-06-27T02:00:00",
                "group": "GROUP_H",
                "type": "group"
            },
            {
                "team1": "Cape Verde Islands",
                "team1_country": "",
                "team2": "Saudi-Arabien",
                "team2_country": "sa",
                "date_str": "Sa, 27. Juni",
                "time": "02:00",
                "venue": "Group H",
                "state": "Finished",
                "score": "0 : 0",
                "full_date": "2026-06-27T02:00:00",
                "group": "GROUP_H",
                "type": "group"
            },
            {
                "team1": "Norwegen",
                "team1_country": "no",
                "team2": "Frankreich",
                "team2_country": "fr",
                "date_str": "Fr, 26. Juni",
                "time": "21:00",
                "venue": "Group I",
                "state": "Finished",
                "score": "1 : 4",
                "full_date": "2026-06-26T21:00:00",
                "group": "GROUP_I",
                "type": "group"
            },
            {
                "team1": "Senegal",
                "team1_country": "sn",
                "team2": "Irak",
                "team2_country": "iq",
                "date_str": "Fr, 26. Juni",
                "time": "21:00",
                "venue": "Group I",
                "state": "Finished",
                "score": "5 : 0",
                "full_date": "2026-06-26T21:00:00",
                "group": "GROUP_I",
                "type": "group"
            },
            {
                "team1": "Türkei",
                "team1_country": "tr",
                "team2": "USA",
                "team2_country": "us",
                "date_str": "Fr, 26. Juni",
                "time": "04:00",
                "venue": "Group D",
                "state": "Finished",
                "score": "3 : 2",
                "full_date": "2026-06-26T04:00:00",
                "group": "GROUP_D",
                "type": "group"
            },
            {
                "team1": "Paraguay",
                "team1_country": "py",
                "team2": "Australien",
                "team2_country": "au",
                "date_str": "Fr, 26. Juni",
                "time": "04:00",
                "venue": "Group D",
                "state": "Finished",
                "score": "0 : 0",
                "full_date": "2026-06-26T04:00:00",
                "group": "GROUP_D",
                "type": "group"
            }
        ],
        "swiss_games": [
            {
                "team1": "Katar",
                "team1_country": "qa",
                "team2": "Schweiz",
                "team2_country": "ch",
                "date_str": "Sa, 13. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "1 : 1",
                "full_date": "2026-06-13T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Bosnia-Herzegovina",
                "team2_country": "",
                "date_str": "Do, 18. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "4 : 1",
                "full_date": "2026-06-18T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Kanada",
                "team2_country": "ca",
                "date_str": "Mi, 24. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "2 : 1",
                "full_date": "2026-06-24T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            }
        ]
    }
};