const dashboardData = {
    "last_updated": "2026-07-04 06:46:04",
    "countdown_target": "2026-06-11T19:00:00",
    "news": [
        {
            "title": "WM 2026: 1/16-Final ARG-CPV - Kap Verde verpasst die Sensation gegen Argentinien nur knapp",
            "date": "04.07.2026",
            "image": "https://www.srf.ch/static/cms/images/320ws/768d7d.webp"
        },
        {
            "title": "WM 2026: 1/16-Final COL-GHA - Kolumbien macht Achtelfinal-Duell mit der Schweiz perfekt",
            "date": "04.07.2026",
            "image": "https://www.srf.ch/static/cms/images/320ws/6f5dab.webp"
        }
    ],
    "schedule": {
        "today_games": [
            {
                "team1": "Argentinien",
                "team1_country": "ar",
                "team2": "Cape Verde Islands",
                "team2_country": "",
                "date_str": "Sa, 4. Juli",
                "time": "00:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "3 : 2",
                "full_date": "2026-07-04T00:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Kolumbien",
                "team1_country": "co",
                "team2": "Ghana",
                "team2_country": "gh",
                "date_str": "Sa, 4. Juli",
                "time": "03:30",
                "venue": "Last 32",
                "state": "Finished",
                "score": "1 : 0",
                "full_date": "2026-07-04T03:30:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Kanada",
                "team1_country": "ca",
                "team2": "Marokko",
                "team2_country": "ma",
                "date_str": "Sa, 4. Juli",
                "time": "19:00",
                "venue": "Last 16",
                "state": "Planned",
                "score": null,
                "full_date": "2026-07-04T19:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Paraguay",
                "team1_country": "py",
                "team2": "Frankreich",
                "team2_country": "fr",
                "date_str": "Sa, 4. Juli",
                "time": "23:00",
                "venue": "Last 16",
                "state": "Planned",
                "score": null,
                "full_date": "2026-07-04T23:00:00",
                "group": null,
                "type": "knockout"
            }
        ],
        "past_results": [
            {
                "team1": "Kolumbien",
                "team1_country": "co",
                "team2": "Ghana",
                "team2_country": "gh",
                "date_str": "Sa, 4. Juli",
                "time": "03:30",
                "venue": "Last 32",
                "state": "Finished",
                "score": "1 : 0",
                "full_date": "2026-07-04T03:30:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Argentinien",
                "team1_country": "ar",
                "team2": "Cape Verde Islands",
                "team2_country": "",
                "date_str": "Sa, 4. Juli",
                "time": "00:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "3 : 2",
                "full_date": "2026-07-04T00:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Australien",
                "team1_country": "au",
                "team2": "Ägypten",
                "team2_country": "eg",
                "date_str": "Fr, 3. Juli",
                "time": "20:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "3 : 5",
                "full_date": "2026-07-03T20:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Algerien",
                "team2_country": "dz",
                "date_str": "Fr, 3. Juli",
                "time": "05:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "2 : 0",
                "full_date": "2026-07-03T05:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Portugal",
                "team1_country": "pt",
                "team2": "Kroatien",
                "team2_country": "hr",
                "date_str": "Fr, 3. Juli",
                "time": "01:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "2 : 1",
                "full_date": "2026-07-03T01:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Spanien",
                "team1_country": "es",
                "team2": "Österreich",
                "team2_country": "at",
                "date_str": "Do, 2. Juli",
                "time": "21:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "3 : 0",
                "full_date": "2026-07-02T21:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "USA",
                "team1_country": "us",
                "team2": "Bosnia-Herzegovina",
                "team2_country": "",
                "date_str": "Do, 2. Juli",
                "time": "02:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "2 : 0",
                "full_date": "2026-07-02T02:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Belgien",
                "team1_country": "be",
                "team2": "Senegal",
                "team2_country": "sn",
                "date_str": "Mi, 1. Juli",
                "time": "22:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "3 : 2",
                "full_date": "2026-07-01T22:00:00",
                "group": null,
                "type": "knockout"
            }
        ],
        "swiss_games": [
            {
                "team1": "Katar",
                "team1_country": "qa",
                "team2": "Schweiz",
                "team2_country": "ch",
                "date_str": "Sa, 13. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "1 : 1",
                "full_date": "2026-06-13T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Bosnia-Herzegovina",
                "team2_country": "",
                "date_str": "Do, 18. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "4 : 1",
                "full_date": "2026-06-18T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Kanada",
                "team2_country": "ca",
                "date_str": "Mi, 24. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "2 : 1",
                "full_date": "2026-06-24T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Algerien",
                "team2_country": "dz",
                "date_str": "Fr, 3. Juli",
                "time": "05:00",
                "venue": "Last 32",
                "state": "Finished",
                "score": "2 : 0",
                "full_date": "2026-07-03T05:00:00",
                "group": null,
                "type": "knockout"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Kolumbien",
                "team2_country": "co",
                "date_str": "Di, 7. Juli",
                "time": "22:00",
                "venue": "Last 16",
                "state": "Planned",
                "score": null,
                "full_date": "2026-07-07T22:00:00",
                "group": null,
                "type": "knockout"
            }
        ]
    }
};