const dashboardData = {
    "last_updated": "2026-06-25 15:25:22",
    "countdown_target": "2026-06-11T19:00:00",
    "news": [
        {
            "title": "SRF-Programm in der Übersicht - DFB-Elf und USA im Rausch: Das läuft am Donnerstag an der WM 2026",
            "date": "25.06.2026",
            "image": "https://www.srf.ch/static/cms/images/320ws/ae579d3.webp"
        },
        {
            "title": "WM 2026: Gruppe E - Bei Deutschland bleibt das grosse Rotieren trotz «Freispiel» aus",
            "date": "25.06.2026",
            "image": "https://www.srf.ch/static/cms/images/320ws/8ee14b.webp"
        }
    ],
    "schedule": {
        "today_games": [
            {
                "team1": "Marokko",
                "team1_country": "ma",
                "team2": "Haiti",
                "team2_country": "ht",
                "date_str": "Do, 25. Juni",
                "time": "00:00",
                "venue": "Group C",
                "state": "Finished",
                "score": "4 : 2",
                "full_date": "2026-06-25T00:00:00",
                "group": "GROUP_C",
                "type": "group"
            },
            {
                "team1": "Schottland",
                "team1_country": "gb-sct",
                "team2": "Brasilien",
                "team2_country": "br",
                "date_str": "Do, 25. Juni",
                "time": "00:00",
                "venue": "Group C",
                "state": "Finished",
                "score": "0 : 3",
                "full_date": "2026-06-25T00:00:00",
                "group": "GROUP_C",
                "type": "group"
            },
            {
                "team1": "Czechia",
                "team1_country": "",
                "team2": "Mexiko",
                "team2_country": "mx",
                "date_str": "Do, 25. Juni",
                "time": "03:00",
                "venue": "Group A",
                "state": "Finished",
                "score": "0 : 3",
                "full_date": "2026-06-25T03:00:00",
                "group": "GROUP_A",
                "type": "group"
            },
            {
                "team1": "Südafrika",
                "team1_country": "za",
                "team2": "Südkorea",
                "team2_country": "kr",
                "date_str": "Do, 25. Juni",
                "time": "03:00",
                "venue": "Group A",
                "state": "Finished",
                "score": "1 : 0",
                "full_date": "2026-06-25T03:00:00",
                "group": "GROUP_A",
                "type": "group"
            },
            {
                "team1": "Ecuador",
                "team1_country": "ec",
                "team2": "Deutschland",
                "team2_country": "de",
                "date_str": "Do, 25. Juni",
                "time": "22:00",
                "venue": "Group E",
                "state": "Planned",
                "score": null,
                "full_date": "2026-06-25T22:00:00",
                "group": "GROUP_E",
                "type": "group"
            },
            {
                "team1": "Curaçao",
                "team1_country": "cw",
                "team2": "Elfenbeinküste",
                "team2_country": "ci",
                "date_str": "Do, 25. Juni",
                "time": "22:00",
                "venue": "Group E",
                "state": "Planned",
                "score": null,
                "full_date": "2026-06-25T22:00:00",
                "group": "GROUP_E",
                "type": "group"
            }
        ],
        "past_results": [
            {
                "team1": "Czechia",
                "team1_country": "",
                "team2": "Mexiko",
                "team2_country": "mx",
                "date_str": "Do, 25. Juni",
                "time": "03:00",
                "venue": "Group A",
                "state": "Finished",
                "score": "0 : 3",
                "full_date": "2026-06-25T03:00:00",
                "group": "GROUP_A",
                "type": "group"
            },
            {
                "team1": "Südafrika",
                "team1_country": "za",
                "team2": "Südkorea",
                "team2_country": "kr",
                "date_str": "Do, 25. Juni",
                "time": "03:00",
                "venue": "Group A",
                "state": "Finished",
                "score": "1 : 0",
                "full_date": "2026-06-25T03:00:00",
                "group": "GROUP_A",
                "type": "group"
            },
            {
                "team1": "Marokko",
                "team1_country": "ma",
                "team2": "Haiti",
                "team2_country": "ht",
                "date_str": "Do, 25. Juni",
                "time": "00:00",
                "venue": "Group C",
                "state": "Finished",
                "score": "4 : 2",
                "full_date": "2026-06-25T00:00:00",
                "group": "GROUP_C",
                "type": "group"
            },
            {
                "team1": "Schottland",
                "team1_country": "gb-sct",
                "team2": "Brasilien",
                "team2_country": "br",
                "date_str": "Do, 25. Juni",
                "time": "00:00",
                "venue": "Group C",
                "state": "Finished",
                "score": "0 : 3",
                "full_date": "2026-06-25T00:00:00",
                "group": "GROUP_C",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Kanada",
                "team2_country": "ca",
                "date_str": "Mi, 24. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "2 : 1",
                "full_date": "2026-06-24T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Bosnia-Herzegovina",
                "team1_country": "",
                "team2": "Katar",
                "team2_country": "qa",
                "date_str": "Mi, 24. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "3 : 1",
                "full_date": "2026-06-24T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Kolumbien",
                "team1_country": "co",
                "team2": "Congo DR",
                "team2_country": "",
                "date_str": "Mi, 24. Juni",
                "time": "04:00",
                "venue": "Group K",
                "state": "Finished",
                "score": "1 : 0",
                "full_date": "2026-06-24T04:00:00",
                "group": "GROUP_K",
                "type": "group"
            },
            {
                "team1": "Panama",
                "team1_country": "pa",
                "team2": "Kroatien",
                "team2_country": "hr",
                "date_str": "Mi, 24. Juni",
                "time": "01:00",
                "venue": "Group L",
                "state": "Finished",
                "score": "0 : 1",
                "full_date": "2026-06-24T01:00:00",
                "group": "GROUP_L",
                "type": "group"
            }
        ],
        "swiss_games": [
            {
                "team1": "Katar",
                "team1_country": "qa",
                "team2": "Schweiz",
                "team2_country": "ch",
                "date_str": "Sa, 13. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "1 : 1",
                "full_date": "2026-06-13T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Bosnia-Herzegovina",
                "team2_country": "",
                "date_str": "Do, 18. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "4 : 1",
                "full_date": "2026-06-18T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            },
            {
                "team1": "Schweiz",
                "team1_country": "ch",
                "team2": "Kanada",
                "team2_country": "ca",
                "date_str": "Mi, 24. Juni",
                "time": "21:00",
                "venue": "Group B",
                "state": "Finished",
                "score": "2 : 1",
                "full_date": "2026-06-24T21:00:00",
                "group": "GROUP_B",
                "type": "group"
            }
        ]
    }
};